---
# tasks file for archiver

- name: Setup newly added tenants
  ansible.builtin.import_tasks: ./add-tenants.yml
  when: archiver_tenants | length > 0

- name: Process removal of pending tenants
  ansible.builtin.import_tasks: ./remove-tenants.yml
  when: archiver_remove_tenants | length > 0
